### ISSUE TITLE
[BUG] 별점평균 컴포넌트 활용시 데이터값이 적용 안되는 버그

### ISSUE THREAD

**Issue by Sin-Sumin** [mariage-kr/mariage#125]
# 개요

별점평균 컴포넌트 활용시 데이터값이 적용 안되는 버그

## 버그 동작 방식

별점평균 컴포넌트를 활용시,
숫자 데이터를 적용시켜도 데이터값에 따른 별점 구현이 안됩니다 

## 정상 동작 방식

별점평균 컴포넌트를 활용시,
숫자 데이터를 적용시켰을 때 데이터값에 따른 별점이 구현되어야 합니다 

## 할 일

별점 컴포넌트 수정

**Comment by KIMSEI1124** [comment]
# 문제 조사

다양한 사이트를 확인 해본 결과 컴포넌트를 호출하는 방식이 아니라 사진 파일을 호출하는 것으로  확인하여 해당 방법으로 수정할 것 입니다.
