### ISSUE TITLE
[BE] 좋아요 등록 기능 구현

### ISSUE THREAD

**Issue by rrimm** [mariage-kr/mariage#201]
# 개요

조건: 리뷰에 대한 좋아요 등록 기능 구현

- 과정
  - 좋아요를 하지 않은 상태인지 확인한다.
  - 좋아요를 등록한다.

## 해결책

리뷰에 대한 좋아요 등록 기능 구현

## 할 일

- 좋아요 비즈니스 로직 구현

## 예시
Controller
```
@PostMapping
    public ResponseEntity<Void> like(@AuthenticationPrincipal Long memberId) {
        likeService.save(memberId);
        return ResponseEntity.ok().build();
    }
```

**Comment by KIMSEI1124** [comment]
# 피드백

1. `@Authenticated` 사용해야합니다!
2. 회원이 이미 좋아요한 상태이면 예외 처리

**Comment by rrimm** [comment]
@KIMSEI1124 확인했습니다. 감사합니다!
